# Generated by Django 4.0.4 on 2024-03-11 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sign_up'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sign_up',
        ),
    ]
